code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension albymor.increment-selection
code --install-extension astro-build.astro-vscode
code --install-extension asvetliakov.snapshot-tools
code --install-extension atlassian.atlascode
code --install-extension aykutsarac.jsoncrack-vscode
code --install-extension azemoh.one-monokai
code --install-extension bradlc.vscode-tailwindcss
code --install-extension charliermarsh.ruff
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension d-biehl.robotcode
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension dotjoshjohnson.xml
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension esbenp.prettier-vscode
code --install-extension figma.figma-vscode-extension
code --install-extension formulahendry.auto-close-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension golang.go
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kevinrose.vsc-python-indent
code --install-extension kortina.vscode-markdown-notes
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension pandy.bun
code --install-extension pnp.polacode
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension robocorp.robocorp-code
code --install-extension robocorp.robotframework-lsp
code --install-extension sandy081.todotasks
code --install-extension shanoor.vscode-nginx
code --install-extension sourcegraph.cody-ai
code --install-extension styled-components.vscode-styled-components
code --install-extension supermaven.supermaven
code --install-extension svelte.svelte-vscode
code --install-extension unifiedjs.vscode-mdx
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension wayou.vscode-todo-highlight
code --install-extension william-voyek.vscode-nginx
code --install-extension xabikos.javascriptsnippets
code --install-extension yzhang.markdown-all-in-one
